config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  get '' => 'dashboard#index'

  resources :classrooms
  resources :courses
  resources :students

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	belongs_to :course
	belongs_to :student

	validates_presence_of :course_id, :student_id
	validates_uniqueness_of :student_id, scope: :course_id, 
													message: I18n.t('activerecord.validations.classroom.uniqueness')

	before_create do
		self.entry_at = Time.now
	end
end

app/models/course.rb
class Course < ActiveRecord::Base
	enum status: [ :active, :inactive ]

	has_many :classrooms, dependent: :destroy
	
	validates_presence_of :name, :description, :status
end

app/models/student.rb
class Student < ActiveRecord::Base
	enum status: [ :active, :inactive ]

	has_many :classrooms, dependent: :destroy

	validates_presence_of :name, :register_number, :status

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  def record_not_found
    render template: 'layouts/record_not_found'
  end

end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
	
	def index
		@classrooms = Classroom.all.order(:entry_at).paginate(page:params[:page], per_page: 10)
	end

	def show
		@classroom = Classroom.find(params[:id])
	end

	def new
		@classroom = Classroom.new
	end

	def create
		@classroom = Classroom.new(permited_params)

		if @classroom.save
			flash[:notice] = I18n.t('flash.success')
			redirect_to @classroom
		else
			render 'new'
		end
	end

	def edit
		@classroom = Classroom.find(params[:id])
	end

	def update
		@classroom = Classroom.find(params[:id])

		if @classroom.update(permited_params)
			flash[:notice] = I18n.t('flash.success')
			redirect_to @classroom
		else
			render 'edit'
		end
	end

	def destroy
    @classroom = Classroom.find(params[:id])
    @classroom.destroy
 
 		flash[:notice] = I18n.t('flash.success')
    redirect_to classrooms_path
  end

	private
	def permited_params
		params.require(:classroom).permit(:course_id, :student_id)
	end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

	def index
		@courses = Course.all.order(:name).paginate(page:params[:page], per_page: 10)
	end

	def show
		@course = Course.find(params[:id])
	end

	def new
		@course = Course.new
	end

	def create
		@course = Course.new(permited_params)

		if @course.save
			flash[:notice] = I18n.t('flash.success')
			redirect_to @course
		else
			render 'new'
		end
	end

	def edit
		@course = Course.find(params[:id])
	end

	def update
		@course = Course.find(params[:id])

		if @course.update(permited_params)
			flash[:notice] = I18n.t('flash.success')
			redirect_to @course
		else
			render 'edit'
		end
	end

	def destroy
    @course = Course.find(params[:id])
    @course.destroy
 		
 		flash[:notice] = I18n.t('flash.success')
    redirect_to courses_path
  end

	private
	def permited_params
		params.require(:course).permit(:name, :description, :status)
	end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

	def index
		@students = Student.all.order(:name).paginate(page:params[:page], per_page: 10)
	end

	def show
		@student = Student.find(params[:id])
	end

	def new
		@student = Student.new
	end

	def create
		@student = Student.new(permited_params)

		if @student.save
			flash[:notice] = I18n.t('flash.success')
			redirect_to @student
		else
			render 'new'
		end
	end

	def edit
		@student = Student.find(params[:id])
	end

	def update
		@student = Student.find(params[:id])

		if @student.update(permited_params)
			flash[:notice] = I18n.t('flash.success')
			redirect_to @student
		else
			render 'edit'
		end
	end

	def destroy
    @student = Student.find(params[:id])
    @student.destroy
 
 		flash[:notice] = I18n.t('flash.success')
    redirect_to students_path
  end

	private
	def permited_params
		params.require(:student).permit(:name, :register_number, :status)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_messages
    flash.collect do |key, msg|
      alert_class = case(key)
      when :notice
        "success"
      when :alert
        "error"
      else
        "info"
      end

      content_tag(:div, msg, :id => key, :class => "alert #{alert_class} center flash-message")
    end.join.html_safe
  end
end

app/helpers/translation_helper.rb
module TranslationHelper
  # Translate model name
  #
  #   <%= tm Post %>
  #   ...
  #   <%= tm Post, 2 %>
  #
  def translate_model_name(model, count = 1)
    model.model_name.human(:count => count)
  end
  alias_method :tm, :translate_model_name

  # Translate model name pluralized
  #
  #   <%= tm Post %>
  #
  def translate_model_name_pluralized(model)
    translate_model_name(model, count = 2)
  end
  alias_method :tmp, :translate_model_name_pluralized

  # Translate a model attribute from config/locales/models-*.yml for more details.
  #
  #   <%= ta Post, :title %>
  #   ...
  #   <%= ta Post, :title, 2 %>
  #
  def translate_model_attribute(model, attribute, count = 1)
    model.human_attribute_name(attribute, :count => count)
  end
  alias_method :ta, :translate_model_attribute
end

app/views/classrooms/_form.html.haml
= form_for @classroom, html: {} do |f|
	.box-body
		- if @classroom.errors.any?
			.alert.alert-danger
				- @classroom.errors.full_messages.each do |m|
					%div
						%i.icon.fa.fa-ban
						= m
		.form-group
			= f.label :course
			= f.select :course_id, Course.all.order(:name).map { |s| [s.name, s.id] },
													{},
               						{ class: 'form-control chosen-select' }
		.form-group
			= f.label :student
			= f.select :student_id, Student.all.order(:name).map { |s| [s.name, s.id] },
													{},
               						{ class: 'form-control chosen-select' }
	.box-footer
		= f.submit class: 'btn btn-primary'

app/views/classrooms/edit.html.haml
.box.box-primary
	.box-header
		%h3.box-title= t 'title.classroom.edit'
		.box-tools
			= link_to(classrooms_path, class: 'btn btn-primary') do
				%i.fa.fa-table
			= link_to(classroom_path(@classroom.id), class: 'btn btn-primary') do
				%i.fa.fa-eye
	= render 'form'

app/views/classrooms/index.html.haml
.box.box-primary
	.box-header
		%h3.box-title= t 'title.classroom.index'
		.box-tools
			= link_to(new_classroom_path, class:'btn btn-success') do
				%i.fa.fa-plus
	.box-body.no-padding
		%table.table.table-hover.table-striped
			%thead
				%tr
					%th= t 'activerecord.attributes.classroom.course'
					%th= t 'activerecord.attributes.classroom.student'
					%th= t 'activerecord.attributes.classroom.entry_at'
					%th.actions= t 'title.actions'
			%tbody
				- @classrooms.each do |classroom|
					%tr
						%td= classroom.course.name
						%td= classroom.student.name
						%td= l classroom.entry_at
						%td
							= link_to(classroom_path(classroom.id), class: 'btn btn-primary') do
								%i.fa.fa-eye
							= link_to(edit_classroom_path(classroom.id), class: 'btn btn-info') do
								%i.fa.fa-pencil
							= link_to(classroom_path(classroom.id), method: :delete, class: 'btn btn-danger', data: {confirm: t('confirmation.destroy')}) do
								%i.fa.fa-trash-o
	.box-footer
		= will_paginate @classrooms, renderer: BootstrapPagination::Rails

app/views/classrooms/new.html.haml
.box.box-primary
	.box-header
		%h3.box-title= t 'title.classroom.new'
		.box-tools
			= link_to(classrooms_path, class: 'btn btn-primary') do
				%i.fa.fa-table
	= render 'form'

app/views/classrooms/show.html.haml
.box.box-primary
	.box-header
		%h3.box-title= t 'title.classroom.show'
		.box-tools
			= link_to(classrooms_path, class: 'btn btn-primary') do
				%i.fa.fa-table
			= link_to(edit_classroom_path(@classroom.id), class: 'btn btn-info') do
				%i.fa.fa-pencil
			= link_to(classroom_path(@classroom.id), method: :delete, class: 'btn btn-danger', data: {confirm: t('confirmation.destroy')}) do
				%i.fa.fa-trash-o
	.box-body.no-padding
		%table.table
			%tbody
				%tr
					%td
						%b= t 'activerecord.attributes.classroom.course'
					%td= @classroom.course.name
				%tr
					%td
						%b= t 'activerecord.attributes.classroom.student'
					%td= @classroom.student.name
				%tr
					%td
						%b= t 'activerecord.attributes.classroom.entry_at'
					%td= l @classroom.entry_at

app/views/courses/_form.html.haml
= form_for @course, html: {} do |f|
	.box-body
		- if @course.errors.any?
			.alert.alert-danger
				- @course.errors.full_messages.each do |m|
					%div
						%i.icon.fa.fa-ban
						= m
		.form-group
			= f.label :name
			= f.text_field :name, class:'form-control'
		.form-group
			= f.label :description
			= f.text_field :description, class:'form-control'
		.form-group
			= f.label :status
			= f.select :status, [[t('enum.active'), :active], [t('enum.inactive'), :inactive]], {}, {class: 'form-control'}
	.box-footer
		= f.submit class: 'btn btn-primary'

app/views/courses/edit.html.haml
.box.box-primary
	.box-header
		%h3.box-title= t 'title.course.edit'
		.box-tools
			= link_to(courses_path, class: 'btn btn-primary') do
				%i.fa.fa-table
			= link_to(course_path(@course.id), class: 'btn btn-primary') do
				%i.fa.fa-eye
	= render 'form'

app/views/courses/index.html.haml
.box.box-primary
	.box-header
		%h3.box-title= t 'title.course.index'
		.box-tools
			= link_to(new_course_path, class:'btn btn-success') do
				%i.fa.fa-plus
	.box-body.no-padding
		%table.table.table-hover.table-striped
			%thead
				%tr
					%th= t 'activerecord.attributes.course.name'
					%th= t 'activerecord.attributes.course.description'
					%th= t 'activerecord.attributes.course.status'
					%th.actions= t 'title.actions'
			%tbody
				- @courses.each do |course|
					%tr
						%td= course.name
						%td= course.description
						%td= t("enum.#{course.status}")
						%td
							= link_to(course_path(course.id), class: 'btn btn-primary') do
								%i.fa.fa-eye
							= link_to(edit_course_path(course.id), class: 'btn btn-info') do
								%i.fa.fa-pencil
							= link_to(course_path(course.id), method: :delete, class: 'btn btn-danger', data: {confirm: t('confirmation.destroy')}) do
								%i.fa.fa-trash-o
	.box-footer
		= will_paginate @courses, renderer: BootstrapPagination::Rails

app/views/courses/new.html.haml
.box.box-primary
	.box-header
		%h3.box-title= t 'title.course.new'
		.box-tools
			= link_to(courses_path, class: 'btn btn-primary') do
				%i.fa.fa-table
	= render 'form'

app/views/courses/show.html.haml
.box.box-primary
	.box-header
		%h3.box-title= t 'title.course.show'
		.box-tools
			= link_to(courses_path, class: 'btn btn-primary') do
				%i.fa.fa-table
			= link_to(edit_course_path(@course.id), class: 'btn btn-info') do
				%i.fa.fa-pencil
			= link_to(course_path(@course.id), method: :delete, class: 'btn btn-danger', data: {confirm: t('confirmation.destroy')}) do
				%i.fa.fa-trash-o
	.box-body.no-padding
		%table.table
			%tbody
				%tr
					%td
						%b= t 'activerecord.attributes.course.name'
					%td= @course.name
				%tr
					%td
						%b= t 'activerecord.attributes.course.description'
					%td= @course.description
				%tr
					%td
						%b= t 'activerecord.attributes.course.status'
					%td= t("enum.#{@course.status}")

app/views/dashboard/index.html.haml
.row
  .col-lg-4.col-xs-12
    .small-box.bg-aqua
      .inner
        %h3= Course.all.count
        %p= t('title.course.menu')
        .icon
          %i.fa.fa-book
      %a.small-box-footer{href:courses_path}= t('title.dashboard.detail')
  .col-lg-4.col-xs-12
    .small-box.bg-green
      .inner
        %h3= Student.all.count
        %p= t('title.student.menu')
        .icon
          %i.fa.fa-user
      %a.small-box-footer{href:students_path}= t('title.dashboard.detail')
  .col-lg-4.col-xs-12
    .small-box.bg-yellow
      .inner
        %h3= Classroom.all.count
        %p= t('title.classroom.menu')
        .icon
          %i.fa.fa-cube
      %a.small-box-footer{href:classrooms_path}= t('title.dashboard.detail')

app/views/layouts/application.html.haml
%html
	%head
		%title= "[IS] #{t('title.application')}"
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tags
	%body.skin-blue
		.wrapper
			%header.main-header
				%a.logo{href:root_path}
					%span.logo-lg
						%b= '[iS]'
						= t 'title.application'
				%nav.navbar.navbar-static-top
			%aside.main-sidebar
				%section.sidebar
					%ul.sidebar-menu
						%li.header
							= 'Menu'
						%li{class:"#{params[:controller] == 'dashboard' ? 'active' : ''}"}
							%a{href:root_path}
								%i.fa.fa-tachometer
								= t 'title.dashboard.menu'
						%li{class:"#{params[:controller] == 'courses' ? 'active' : ''}"}
							%a{href:courses_path}
								%i.fa.fa-book
								= t 'title.course.menu'
						%li{class:"#{params[:controller] == 'students' ? 'active' : ''}"}
							%a{href:students_path}
								%i.fa.fa-user
								= t 'title.student.menu'
						%li{class:"#{params[:controller] == 'classrooms' ? 'active' : ''}"}
							%a{href:classrooms_path}
								%i.fa.fa-cube
								= t 'title.classroom.menu'
			.content-wrapper
				%section.content
					- if flash[:notice]
						.alert.alert-success.alert-dismissable
							%button.close{type: 'button', "data-dismiss" => "alert"}= 'x'
							%i.icon.fa.fa-check
							= flash[:notice]
					= yield

app/views/layouts/record_not_found.html.haml
.error-page
  %h2.headline.text-yellow= '404'
  .error-content
    %h3
      %i.fa.fa-warning.text-yellow
      = 'Oops! Page not found.'
    %p
      = 'We could not find the page you were looking for. Meanwhile, you may '
      %a{href: root_path}= 'return to dashboard'

app/views/students/_form.html.haml
= form_for @student, html: {} do |f|
	.box-body
		- if @student.errors.any?
			.alert.alert-danger
				- @student.errors.full_messages.each do |m|
					%div
						%i.icon.fa.fa-ban
						= m
		.form-group
			= f.label :name
			= f.text_field :name, class:'form-control'
		.form-group
			= f.label :register_number
			= f.text_field :register_number, class:'form-control'
		.form-group
			= f.label :status
			= f.select :status, [[t('enum.active'), :active], [t('enum.inactive'), :inactive]], {}, {class: 'form-control'}
	.box-footer
		= f.submit class: 'btn btn-primary'

app/views/students/edit.html.haml
.box.box-primary
	.box-header
		%h3.box-title= t 'title.student.edit'
		.box-tools
			= link_to(students_path, class: 'btn btn-primary') do
				%i.fa.fa-table
			= link_to(student_path(@student.id), class: 'btn btn-primary') do
				%i.fa.fa-eye
	= render 'form'

app/views/students/index.html.haml
.box.box-primary
	.box-header
		%h3.box-title= t 'title.student.index'
		.box-tools
			= link_to(new_student_path, class:'btn btn-success') do
				%i.fa.fa-plus
	.box-body.no-padding
		%table.table.table-condensed.table-hover.table-striped
			%thead
				%tr
					%th= t 'activerecord.attributes.student.name'
					%th= t 'activerecord.attributes.student.register_number'
					%th= t 'activerecord.attributes.student.status'
					%th.actions= t 'title.actions'
			%tbody
				- @students.each do |student|
					%tr
						%td= student.name
						%td= student.register_number
						%td= t("enum.#{student.status}")
						%td
							= link_to(student_path(student.id), class: 'btn btn-primary') do
								%i.fa.fa-eye
							= link_to(edit_student_path(student.id), class: 'btn btn-info') do
								%i.fa.fa-pencil
							= link_to(student_path(student.id), method: :delete, class: 'btn btn-danger', data: {confirm: t('confirmation.destroy')}) do
								%i.fa.fa-trash-o
	.box-footer
		= will_paginate @students, renderer: BootstrapPagination::Rails

app/views/students/new.html.haml
.box.box-primary
	.box-header
		%h3.box-title= t 'title.student.new'
		.box-tools
			= link_to(students_path, class: 'btn btn-primary') do
				%i.fa.fa-table
	= render 'form'

app/views/students/show.html.haml
.box.box-primary
	.box-header
		%h3.box-title= t 'title.student.show'
		.box-tools
			= link_to(students_path, class: 'btn btn-primary') do
				%i.fa.fa-table
			= link_to(edit_student_path(@student.id), class: 'btn btn-info') do
				%i.fa.fa-pencil
			= link_to(student_path(@student.id), method: :delete, class: 'btn btn-danger', data: {confirm: t('confirmation.destroy')}) do
				%i.fa.fa-trash-o
	.box-body.no-padding
		%table.table
			%tbody
				%tr
					%td
						%b= t 'activerecord.attributes.student.name'
					%td= @student.name
				%tr
					%td
						%b= t 'activerecord.attributes.student.register_number'
					%td= @student.register_number
				%tr
					%td
						%b= t 'activerecord.attributes.student.status'
					%td= t("enum.#{@student.status}")